version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: eslint-plugin-jsdoc
    versions:
    - 31.6.0
    - 32.0.0
    - 32.1.0
    - 32.1.1
    - 32.3.1
  - dependency-name: eslint
    versions:
    - 7.24.0
  - dependency-name: "@commitlint/config-conventional"
    versions:
    - 12.0.1
  - dependency-name: husky
    versions:
    - 5.1.0
    - 5.1.2
